apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-7nhj
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0060-tenant/tkrw-pr712-0075-0060-app/devfile-sample-7nhj@sha256:af3f6f68eeed3d2072454ed243309b3d3d2c7f51c2f33a6f6a5469a7ab604aa4
        name: my-nodejs
        resources: {}
status: {}
